# Section 5: Job Artifacts & Outputs

# Sample Artifacts (Output Asset(s)):
## Docker Image
## App Store Packages
## Desktop Application
## Anything

name: Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # https://github.com/marketplace/actions/cache
      # since runners change per execution, cached dependencies will not be available by default
      # this step must be placed before all "Install Dependencies" step
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # ~/.npm - Internal NPM dependency cache
          # this step will also automatically look up to ~/.npm directory after the job finished and put that directory into the cache if it doesn't exist
          path: |
            ~/.npm
          # key for retrieving the cache
          # hashFiles: https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles
          # builds a hash of all `package-lock.json` files from all directories
          # dependency key must be dynamic to indicate removal of outdated cache
          key: dependency-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
      # steps.<step id>.outputs.<step output key>
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # https://github.com/marketplace/actions/cache
      # since runners change per execution, cached dependencies will not be available by default
      # this step must be placed before all "Install Dependencies" step
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # ~/.npm - Internal NPM dependency cache
          # this step will also automatically look up to ~/.npm directory after the job finished and put that directory into the cache if it doesn't exist
          path: |
            ~/.npm
          # key for retrieving the cache
          # hashFiles: https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles
          # builds a hash of all `package-lock.json` files from all directories
          # dependency key must be dynamic to indicate removal of outdated cache
          key: dependency-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci  # will automatically use ~/.npm directory. will be used when existing, otherwise downloaded
      - name: Build
        run: npm run build  # stores output to "dist" directory
      - name: Publish JS filename
        # id field is required for defining output
        id: publish
        # Store to special file $GITHUB_OUTPUT managed by github
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          # Supports multiple paths and patterns
          path: |
            dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download and unzip "dist-files" artifact
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          # by default, files will be placed on current directory (files only excluding top level directory)
          path: dist
      - name: Output contents
        run: ls
      - name: Output filename
        # https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying ..."
