name: Output Event Details

# on: issues
on: workflow_dispatch

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: echo "${{ toJSON(github.event) }}"
